# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.postgresql.superuserSecretName }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  data:
    - remoteRef:
        key: airm-cnpg-superuser-username
        property: value
      secretKey: username
    - remoteRef:
        key: airm-cnpg-superuser-password
        property: value
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecretStore }}
  target:
    name: "{{ .Values.postgresql.superuserSecretName }}"
    template:
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.postgresql.userSecretName }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  data:
    - remoteRef:
        key: airm-cnpg-user-username
        property: value
      secretKey: username
    - remoteRef:
        key: airm-cnpg-user-password
        property: value
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecretStore }}
  target:
    name: "{{ .Values.postgresql.userSecretName }}"
    template:
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.keycloak.adminClientSecretName }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  data:
    - remoteRef:
        key: airm-keycloak-admin-client-id
        property: value
      secretKey: client-id
    - remoteRef:
        key: airm-keycloak-admin-client-secret
        property: value
      secretKey: client-secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecretStore }}
  target:
    name: "{{ .Values.keycloak.adminClientSecretName }}"
    template:
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.rabbitmq.adminUserSecretName }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  data:
    - remoteRef:
        key: airm-rabbitmq-user-username
        property: value
      secretKey: username
    - remoteRef:
        key: airm-rabbitmq-user-password
        property: value
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecretStore }}
  target:
    name: "{{ .Values.rabbitmq.adminUserSecretName }}"
    template:
      data:
        default_user.conf: |
          default_user = {{ "{{ .username }}" }}
          default_pass = {{ "{{ .password }}" }}
        password: '{{ "{{ .password }}" }}'
        username: '{{ "{{ .username }}" }}'
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.ui.secretName }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  data:
    - remoteRef:
        key: airm-ui-auth-nextauth-secret
        property: value
      secretKey: NEXTAUTH_SECRET
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecretStore }}
  target:
    name: "{{ .Values.ui.secretName }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.keycloak.uiClientSecretName }}
  namespace: "{{ .Release.Namespace }}"
spec:
  data:
    - remoteRef:
        key: airm-ui-keycloak-secret
        property: value
      secretKey: KEYCLOAK_SECRET
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecretStore }}
  target:
    name: {{ .Values.keycloak.uiClientSecretName }}
    template:
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.keycloak.userCredentialsSecretName }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  data:
    - remoteRef:
        key: keycloak-initial-devuser-password
        property: value
      secretKey: USER_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecretStore }}
  target:
    name: {{ .Values.keycloak.userCredentialsSecretName }}
    template:
      type: Opaque
