{
 "title": "Persitent volumes dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "k8s_cluster_name",
    "label": "k8s_cluster_name",
    "query": {
     "query": "label_values(kubelet_volume_stats_used_bytes,k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kubelet_volume_stats_used_bytes{k8s_cluster_name=\"$k8s_cluster_name\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Used percentage (Top 10)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OCI1 Used percentage(Top 10)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \n  kubelet_volume_stats_used_bytes{k8s_cluster_name=\"oci1\"} \n  / \n  kubelet_volume_stats_capacity_bytes{k8s_cluster_name=\"oci1\"}\n)\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "OCI2 Used percentage(Top 10)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \n  kubelet_volume_stats_used_bytes{k8s_cluster_name=\"oci2\"} \n  / \n  kubelet_volume_stats_capacity_bytes{k8s_cluster_name=\"oci2\"}\n)\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "Cluster / Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Used bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Used percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\", namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{k8s_cluster_name=~\"$k8s_cluster_name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Weekly Volume Use Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes{k8s_cluster_name=~\"$k8s_cluster_name\",namespace=~\"$namespace\"} [1w])",
     "legendFormat": "({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Volume capacity bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{k8s_cluster_name=~\"$k8s_cluster_name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}