---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cluster-auth.fullname" . }}-restart-envoygateway
  namespace: {{ .Values.namespace.name }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "cluster-auth.fullname" . }}-restart-envoygateway-sa
      containers:
        - name: restart
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl wait deployment {{ include "cluster-auth.fullname" . }} -n {{ .Values.namespace.name }} --for=condition=Available=True --timeout=180s
              kubectl rollout restart deployment -l gateway.envoyproxy.io/owning-gateway-name=https -n envoy-gateway-system
      restartPolicy: Never
