# metallb-system/memberlist
apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
type: Opaque
stringData:
  secretkey: placeholder

---
# workbench/minio-credentials (standalone mode only)
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: workbench
type: Opaque
stringData:
  minio-access-key: placeholder
  minio-secret-key: placeholder