apiVersion: v1
kind: Service
metadata:
  name: https
  namespace: envoy-gateway-system
spec:
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway
    app.kubernetes.io/name: envoy
    gateway.envoyproxy.io/owning-gateway-name: https
    gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
  ports:
  - name: https-443
    port: 443
    protocol: TCP
    targetPort: 10443
  type: ClusterIP
