apiVersion: v1
kind: ConfigMap
data:
  CERT_OPTION: generate
  DISABLED_STEPS: SetupLonghornStep
  DOMAIN: localhost
  GPU_NODE: "false"
  SKIP_DISK_CHECK: "true"
  TLS_CERT: none
  TLS_KEY: none
  USE_CERT_MANAGER: "false"
  tls_secret_name: none
  tls_secret_namespace: kgateway-system
metadata:
  name: bloom
  namespace: default

