# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: '{{ .Release.Name }}-rabbitmq'
  namespace: '{{ .Release.Namespace }}'
spec:
  persistence:
    {{- toYaml .Values.persistence | nindent 4 }}
  replicas: {{ .Values.replicas }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
  secretBackend:
    externalSecret:
      name: '{{ .Values.adminSecretName }}'
  tls:
    secretName: '{{ .Values.tlsSecretName }}'
