{{- $families := include "aim.hardwareFamilies" . | fromJsonArray }}
{{- if has "radeon" $families }}
---
apiVersion: aim.eai.amd.com/v1alpha1
kind: AIMClusterModelSource
metadata:
  name: amd-aim-radeon-0.12.0
spec:
  filters:
    # - image: amdenterpriseai/aim-radeon-base:0.12-preview
    - image: amdenterpriseai/aim-radeon-google-gemma-3n-e4b-it:0.12.0-preview
    - image: amdenterpriseai/aim-radeon-meta-llama-llama-3-1-8b-instruct:0.12.0-preview
    - image: amdenterpriseai/aim-radeon-qwen-qwen3-5-9b:0.12.0-preview
    - image: amdenterpriseai/aim-radeon-qwen-qwen3-vl-8b-instruct:0.12.0-preview
    - image: amdenterpriseai/aim-radeon-zai-org-glm-4-7-flash:0.12.0-preview
  maxModels: 100
  registry: docker.io
  syncInterval: 1h
{{- end }}
