apiVersion: v2
name: aiwb-demo-secrets
description: Every Secret of the aiwb-demo profile
type: application
version: 0.1.0
dependencies:
  - name: aiwb-demo-secrets
    version: 0.1.0
    repository: file://../../../sources/aiwb-demo-secrets
