apiVersion: v2
name: kserve
description: KServe model serving control plane
type: application
version: 0.1.0
dependencies:
  - name: kserve
    version: v0.16.0
    repository: file://../../../sources/kserve/v0.16.0
