#!/bin/bash
# RKE2 Kubernetes cluster setup — extracted from silogen/cluster-bloom
# Usage: sudo bash setup-rke2.sh [domain]
#   If domain is omitted, uses <public-ip>.nip.io automatically

set -euo pipefail

# ============================================================
# DOMAIN RESOLUTION
# ============================================================
if [ -n "${1:-}" ]; then
  DOMAIN="${1}"
else
  echo "==> No domain provided, detecting public IP for nip.io..."
  PUBLIC_IP=$(curl -sf https://icanhazip.com || curl -sf https://ifconfig.me || echo "")
  if [ -z "${PUBLIC_IP}" ]; then
    echo "❌ Could not detect public IP. Please pass a domain as argument."
    exit 1
  fi
  DOMAIN="${PUBLIC_IP}.nip.io"
  echo "==> Using domain: ${DOMAIN}"
fi

NODE_IP=$(ip route get 1.1.1.1 | grep -oP 'src \K\S+')

echo "==> Domain:  ${DOMAIN}"
echo "==> Node IP: ${NODE_IP}"

# ============================================================
# 1. PACKAGES
# ============================================================
echo "==> Installing required packages..."
systemctl stop unattended-upgrades.service apt-daily.timer apt-daily-upgrade.timer 2>/dev/null || true
sleep 3
rm -f /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/lib/dpkg/lock*
dpkg --configure -a 2>/dev/null || true

apt-get update -y
DEBIAN_FRONTEND=noninteractive apt-get install -y \
  open-iscsi jq nfs-common chrony curl wget iptables

# ============================================================
# 2. KERNEL MODULES
# ============================================================
echo "==> Loading kernel modules..."
modprobe iscsi_tcp
modprobe dm_mod
cat > /etc/modules-load.d/rke2.conf <<'EOF'
iscsi_tcp
dm_mod
EOF

# ============================================================
# 3. SYSTEM CONFIG (inotify + firewall ports)
# ============================================================
echo "==> Configuring system..."
sysctl -w fs.inotify.max_user_instances=512
echo "fs.inotify.max_user_instances=512" >> /etc/sysctl.conf

for port in 80 443 2376 2379 2380 6443 9099 9345 10250 10254; do
  iptables -I INPUT -p tcp --dport ${port} -m state --state NEW -j ACCEPT 2>/dev/null || true
done
iptables -I INPUT -p tcp --dport 30000:32767 -m state --state NEW -j ACCEPT 2>/dev/null || true
iptables -I INPUT -p udp --dport 8472 -m state --state NEW -j ACCEPT 2>/dev/null || true
iptables -I INPUT -p udp --dport 30000:32767 -m state --state NEW -j ACCEPT 2>/dev/null || true

# ============================================================
# 4. RKE2 CONFIGURATION
# ============================================================
echo "==> Writing RKE2 config..."
mkdir -p /etc/rancher/rke2

# DNS for RKE2
if grep -q "127\.0\.0\." /etc/resolv.conf && [ -f /run/systemd/resolve/resolv.conf ]; then
  echo "# Generated by cluster-bloom from systemd-resolved" > /etc/rancher/rke2/resolv.conf
  grep -v '^search ' /run/systemd/resolve/resolv.conf | grep -E '^(nameserver|options)' >> /etc/rancher/rke2/resolv.conf
else
  echo "# Generated by cluster-bloom from host resolv.conf" > /etc/rancher/rke2/resolv.conf
  grep -v '^search ' /etc/resolv.conf | grep -E '^(nameserver|options)' >> /etc/rancher/rke2/resolv.conf
fi

# Audit policy
cat > /etc/rancher/rke2/audit-policy.yaml <<'EOF'
apiVersion: audit.k8s.io/v1
kind: Policy
metadata:
  creationTimestamp: null
rules:
  - level: Metadata
EOF

# Main RKE2 config
cat > /etc/rancher/rke2/config.yaml <<EOF
cni: cilium
cluster-cidr: 10.242.0.0/16
service-cidr: 10.243.0.0/16
node-ip: ${NODE_IP}
disable: rke2-ingress-nginx
audit-log-path: "/var/lib/rancher/rke2/server/logs/kube-apiserver-audit.log"
audit-log-maxage: 30
audit-log-maxbackup: 10
audit-log-maxsize: 100
audit-policy-file: "/etc/rancher/rke2/audit-policy.yaml"
resolv-conf: "/etc/rancher/rke2/resolv.conf"
tls-san:
  - "${NODE_IP}"
  - "k8s.${DOMAIN}"
EOF

# ============================================================
# 5. INSTALL & START RKE2
# ============================================================
echo "==> Installing RKE2..."
curl -sfL https://get.rke2.io | sh -

echo "==> Enabling and starting rke2-server..."
systemctl enable rke2-server
systemctl start rke2-server

echo "==> Waiting for RKE2 to be ready (up to 5 min)..."
timeout 300 bash -c 'until [ -f /var/lib/rancher/rke2/server/node-token ]; do sleep 2; done'
echo "    RKE2 is up."

# ============================================================
# 6. KUBECONFIG
# ============================================================
echo "==> Setting up kubeconfig..."
mkdir -p /root/.kube
cp /etc/rancher/rke2/rke2.yaml /root/.kube/config
sed -i "s/127\.0\.0\.1/${NODE_IP}/g" /root/.kube/config
chmod 600 /root/.kube/config

if [ -n "${SUDO_USER:-}" ]; then
  USER_HOME=$(getent passwd "${SUDO_USER}" | cut -d: -f6)
  mkdir -p "${USER_HOME}/.kube"
  cp /etc/rancher/rke2/rke2.yaml "${USER_HOME}/.kube/config"
  sed -i "s/127\.0\.0\.1/${NODE_IP}/g" "${USER_HOME}/.kube/config"
  chown -R "${SUDO_USER}:${SUDO_USER}" "${USER_HOME}/.kube"
  chmod 600 "${USER_HOME}/.kube/config"
fi

# ============================================================
# 7. CLI TOOLS (kubectl, helm, yq, k9s)
# ============================================================
echo "==> Installing kubectl..."
curl -sLo /usr/local/bin/kubectl https://dl.k8s.io/release/v1.34.2/bin/linux/amd64/kubectl
chmod +x /usr/local/bin/kubectl

echo "==> Installing helm..."
curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash

echo "==> Installing yq..."
curl -sLo /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.46.1/yq_linux_amd64
chmod +x /usr/local/bin/yq

echo "==> Installing k9s..."
K9S_VERSION=$(curl -s https://api.github.com/repos/derailed/k9s/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
curl -sL "https://github.com/derailed/k9s/releases/download/v${K9S_VERSION}/k9s_Linux_amd64.tar.gz" | tar xz -C /tmp k9s
mv /tmp/k9s /usr/local/bin/k9s
chmod +x /usr/local/bin/k9s

export PATH="/var/lib/rancher/rke2/bin:${PATH}"
echo 'export PATH="/var/lib/rancher/rke2/bin:$PATH"' >> /etc/profile.d/rke2.sh
echo 'export KUBECONFIG=/root/.kube/config' >> /etc/profile.d/rke2.sh

# ============================================================
# DONE
# ============================================================
echo ""
echo "✅ RKE2 cluster is ready!"
echo ""
echo "   Node IP:  ${NODE_IP}"
echo "   Domain:   ${DOMAIN}"
echo ""
echo "   Verify:"
echo "   export KUBECONFIG=/root/.kube/config"
echo "   kubectl get nodes"
echo ""
echo "   Join token (for additional nodes):"
echo "   $(cat /var/lib/rancher/rke2/server/node-token)"

exit 0