{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "envoy-gateway-metrics-collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "envoy-gateway-metrics-collector.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
