apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  creationTimestamp: '2025-10-01T17:54:45Z'
  generation: 1
  labels:
    airm.silogen.ai/component-id: 082caca5-ae29-4b31-b998-e97d93aab84f
    airm.silogen.ai/project-id: 2f16e137-9b80-4019-93aa-1c14f475beef
    airm.silogen.ai/workload-id: 134b135d-aeb6-44b2-b368-186b28c81620
  managedFields:
    - apiVersion: gateway.networking.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:airm.silogen.ai/component-id: {}
            f:airm.silogen.ai/project-id: {}
            f:airm.silogen.ai/workload-id: {}
        f:spec:
          .: {}
          f:parentRefs: {}
          f:rules: {}
      manager: OpenAPI-Generator
      operation: Update
      time: '2025-10-01T17:54:45Z'
    - apiVersion: gateway.networking.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:parents: {}
      manager: kgateway
      operation: Update
      subresource: status
      time: '2025-10-01T17:54:45Z'
  name: mw-dev-workspace-jupyterlab-1759341285-134b
  namespace: demo
  resourceVersion: '1356131'
  uid: 3ab9852e-3c20-40eb-841b-5e0923ea93b2
  selfLink: >-
    /apis/gateway.networking.k8s.io/v1/namespaces/demo/httproutes/mw-dev-workspace-jupyterlab-1759341285-134b
status:
  parents:
    - conditions:
        - lastTransitionTime: '2025-10-01T17:54:45Z'
          message: Route is accepted
          observedGeneration: 1
          reason: Accepted
          status: 'True'
          type: Accepted
        - lastTransitionTime: '2025-10-01T17:54:45Z'
          message: Route has valid refs
          observedGeneration: 1
          reason: ResolvedRefs
          status: 'True'
          type: ResolvedRefs
      controllerName: kgateway.dev/kgateway
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: https
        namespace: kgateway-system
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: https
      namespace: kgateway-system
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: mw-dev-workspace-jupyterlab-1759341285-134b
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: >-
              /2f16e137-9b80-4019-93aa-1c14f475beef/3015d2c4-1681-4825-8cfe-40cf6a916660/134b135d-aeb6-44b2-b368-186b28c81620
