# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

---
apiVersion: v2
name: airm-cnpg
description: CNPG PostgreSQL cluster infrastructure for AIRM

type: application

version: 0.1.0

appVersion: "0.1.0"
