# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

---
apiVersion: v2
name: aiwb
description: AIWB (AI Workbench) - API and UI services for AI workload management

type: application

# Chart version
version: 1.0.31

# Workbench version
appVersion: "1.0.3"
