{
 "title": "AMD GPU Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "scope",
    "label": "Scope",
    "query": "kubernetes-pods,kubernetes-service-endpoints"
   },
   { "name": "node", "label": "Node", "query": { "query": "label_values(node)" } },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values({node=\"$node\"},gpu_uuid)"
    }
   },
   {
    "name": "gpu_family",
    "label": "GPU Family",
    "query": {
     "query": "label_values({gpu_uuid=\"$gpu\"},amd_com_gpu_family)"
    }
   },
   {
    "name": "gpu_model",
    "label": "GPU Model",
    "query": {
     "query": "label_values({gpu_uuid=~\"$gpu\"},card_model)"
    }
   },
   {
    "name": "gpu_serial_number",
    "label": "GPU Serial Number",
    "query": {
     "query": "label_values({gpu_uuid=~\"$gpu\"},serial_number)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "**GPU MODEL**\n## ${gpu_model}\n\n**GPU S/N**\n## ${gpu_serial_number}"
   }
  },
  {
   "title": "Power Usage (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_power_usage{gpu_uuid=~\"$gpu\", job=\"$scope\"}",
     "legendFormat": "gpu_power_usage"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_used_vram{gpu_uuid=~\"$gpu\", job=\"$scope\"} / on(gpu_uuid) gpu_total_vram{gpu_uuid=~\"$gpu\", job=\"$scope\"}",
     "legendFormat": "gpu_vram_utilization"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_gfx_activity{gpu_uuid=~\"$gpu\", job=\"$scope\"}",
     "legendFormat": "gpu_gfx_activity"
    }
   ]
  },
  {
   "title": "GPU Temperature °C",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_edge_temperature{gpu_uuid=~\"$gpu\", job=\"$scope\"}",
     "legendFormat": "gpu_edge_temperature"
    }
   ]
  },
  {
   "title": "VRAM Usage (MB)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_used_vram{gpu_uuid=~\"$gpu\", job=\"$scope\"}",
     "legendFormat": "gpu_used_vram"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "gpu_gfx_activity{gpu_uuid=~\"$gpu\", job=\"$scope\"}",
     "legendFormat": "{{gpu_uuid}}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gpu_used_vram{gpu_uuid=~\"$gpu\", job=\"$scope\"} / on(gpu_uuid) gpu_total_vram{gpu_uuid=~\"$gpu\", job=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temperature °C",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_edge_temperature{gpu_uuid=~\"$gpu\", job=\"$scope\"}",
     "legendFormat": "{{gpu_uuid}}"
    }
   ]
  },
  {
   "title": "Raw data",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{gpu_uuid=~\"$gpu\", job=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}