{
 "title": "Data Dashboard",
 "tags": [ "rayVersion:2.9.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "SessionName",
    "query": {
     "query": "label_values(ray_data_allocated_bytes{}, SessionName)"
    }
   },
   {
    "name": "DatasetID",
    "query": {
     "query": "label_values(ray_data_allocated_bytes{}, dataset)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes Spilled",
   "type": "graph",
   "description": "Amount spilled by dataset operators. DataContext.enable_get_object_locations_for_metrics must be set to True to report this metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_spilled_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Spilled: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Bytes Allocated",
   "type": "graph",
   "description": "Amount allocated by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_allocated_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Allocated: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Bytes Freed",
   "type": "graph",
   "description": "Amount freed by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_freed_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Freed: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Object Store Memory",
   "type": "graph",
   "description": "Amount of memory store used by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_current_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Current Usage: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "CPUs (logical slots)",
   "type": "graph",
   "description": "Logical CPUs allocated to dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_cpu_usage_cores{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "CPU Usage: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "GPUs (logical slots)",
   "type": "graph",
   "description": "Logical GPUs allocated to dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_gpu_usage_cores{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "GPU Usage: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Bytes Outputted",
   "type": "graph",
   "description": "Total bytes outputted by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_output_bytes{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Bytes Outputted: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Rows Outputted",
   "type": "graph",
   "description": "Total rows outputted by dataset operators.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "rows" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_output_rows{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Rows Outputted: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Block Generation Time",
   "type": "graph",
   "description": "Time spent generating blocks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_block_generation_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset, operator)",
     "legendFormat": "Block Generation Time: {{dataset}}, {{operator}}"
    }
   ]
  },
  {
   "title": "Iteration Blocked Time",
   "type": "graph",
   "description": "Seconds user thread is blocked by iter_batches()",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_iter_total_blocked_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset)",
     "legendFormat": "Seconds: {{dataset}}"
    }
   ]
  },
  {
   "title": "Iteration User Time",
   "type": "graph",
   "description": "Seconds spent in user code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(ray_data_iter_user_seconds{dataset=~\"$DatasetID\",SessionName=~\"$SessionName\",}) by (dataset)",
     "legendFormat": "Seconds: {{dataset}}"
    }
   ]
  }
 ]
}
{
 "title": "Default Dashboard",
 "tags": [ "rayVersion:2.9.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "SessionName",
    "query": {
     "query": "label_values(ray_node_network_receive_speed{}, SessionName)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(ray_node_network_receive_speed{SessionName=\"$SessionName\",}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Scheduler Task State",
   "type": "graph",
   "description": "Current number of tasks in a particular state.\n\nState: the task state, as described by rpc::TaskState proto in common.proto. Task resubmissions due to failures or object reconstruction are shown with (retry) in the label.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(ray_tasks{IsRetry=\"0\",State=~\"FINISHED|FAILED\",SessionName=~\"$SessionName\",}[14d])) by (State) or clamp_min(sum(ray_tasks{IsRetry=\"0\",State!~\"FINISHED|FAILED\",SessionName=~\"$SessionName\",}) by (State), 0)",
     "legendFormat": "{{State}}"
    },
    {
     "expr": "sum(max_over_time(ray_tasks{IsRetry!=\"0\",State=~\"FINISHED|FAILED\",SessionName=~\"$SessionName\",}[14d])) by (State) or clamp_min(sum(ray_tasks{IsRetry!=\"0\",State!~\"FINISHED|FAILED\",SessionName=~\"$SessionName\",}) by (State), 0)",
     "legendFormat": "{{State}} (retry)"
    }
   ]
  },
  {
   "title": "Active Tasks by Name",
   "type": "graph",
   "description": "Current number of (live) tasks with a particular name. Task resubmissions due to failures or object reconstruction are shown with (retry) in the label.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_tasks{IsRetry=\"0\",State!~\"FINISHED|FAILED\",SessionName=~\"$SessionName\",}) by (Name)",
     "legendFormat": "{{Name}}"
    },
    {
     "expr": "sum(ray_tasks{IsRetry!=\"0\",State!~\"FINISHED|FAILED\",SessionName=~\"$SessionName\",}) by (Name)",
     "legendFormat": "{{Name}} (retry)"
    }
   ]
  },
  {
   "title": "Scheduler Actor State",
   "type": "graph",
   "description": "Current number of actors in a particular state.\n\nState: the actor state, as described by rpc::ActorTableData proto in gcs.proto.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "actors" }
   ],
   "targets": [
    {
     "expr": "sum(ray_actors{SessionName=~\"$SessionName\",}) by (State)",
     "legendFormat": "{{State}}"
    }
   ]
  },
  {
   "title": "Active Actors by Name",
   "type": "graph",
   "description": "Current number of (live) actors with a particular name.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "actors" }
   ],
   "targets": [
    {
     "expr": "sum(ray_actors{State!=\"DEAD\",SessionName=~\"$SessionName\",}) by (Name)",
     "legendFormat": "{{Name}}"
    }
   ]
  },
  {
   "title": "Scheduler CPUs (logical slots)",
   "type": "graph",
   "description": "Logical CPU usage of Ray. The dotted line indicates the total number of CPUs. The logical CPU is allocated by `num_cpus` arguments from tasks and actors. PENDING means the number of CPUs that will be available when new nodes are up after the autoscaler scales up.\n\nNOTE: Ray's logical CPU is different from physical CPU usage. Ray's logical CPU is allocated by `num_cpus` arguments.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_resources{Name=\"CPU\",State=\"USED\",SessionName=~\"$SessionName\",}) by (instance)",
     "legendFormat": "CPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"CPU\",SessionName=~\"$SessionName\",})",
     "legendFormat": "MAX"
    },
    {
     "expr": "((sum(autoscaler_cluster_resources{resource=\"CPU\",SessionName=~\"$SessionName\",}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"CPU\",SessionName=~\"$SessionName\",}) or vector(0)) and (sum(autoscaler_cluster_resources{resource=\"CPU\",SessionName=~\"$SessionName\",}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"CPU\",SessionName=~\"$SessionName\",}) or vector(0)) > (sum(autoscaler_cluster_resources{resource=\"CPU\",SessionName=~\"$SessionName\",}) or vector(0)))",
     "legendFormat": "MAX + PENDING"
    }
   ]
  },
  {
   "title": "Object Store Memory",
   "type": "graph",
   "description": "Object store memory usage by location. The dotted line indicates the object store memory capacity.\n\nLocation: where the memory was allocated, which is MMAP_SHM or MMAP_DISK to indicate memory-mapped page, SPILLED to indicate spillage to disk, and WORKER_HEAP for objects small enough to be inlined in worker memory. Refer to metric_defs.cc for more information.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_object_store_memory{SessionName=~\"$SessionName\",}) by (Location)",
     "legendFormat": "{{Location}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"object_store_memory\",SessionName=~\"$SessionName\",})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Scheduler GPUs (logical slots)",
   "type": "graph",
   "description": "Logical GPU usage of Ray. The dotted line indicates the total number of GPUs. The logical GPU is allocated by `num_gpus` arguments from tasks and actors. PENDING means the number of GPUs that will be available when new nodes are up after the autoscaler scales up.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "GPUs" }
   ],
   "targets": [
    {
     "expr": "ray_resources{Name=\"GPU\",State=\"USED\",SessionName=~\"$SessionName\",}",
     "legendFormat": "GPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"GPU\",SessionName=~\"$SessionName\",})",
     "legendFormat": "MAX"
    },
    {
     "expr": "((sum(autoscaler_cluster_resources{resource=\"GPU\",SessionName=~\"$SessionName\",}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"GPU\",SessionName=~\"$SessionName\",}) or vector(0)) and (sum(autoscaler_cluster_resources{resource=\"GPU\",SessionName=~\"$SessionName\",}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"GPU\",SessionName=~\"$SessionName\",}) or vector(0)) > (sum(autoscaler_cluster_resources{resource=\"GPU\",SessionName=~\"$SessionName\",}) or vector(0)))",
     "legendFormat": "MAX + PENDING"
    }
   ]
  },
  {
   "title": "Scheduler Placement Groups",
   "type": "graph",
   "description": "Current number of placement groups in a particular state.\n\nState: the placement group state, as described by the rpc::PlacementGroupTable proto in gcs.proto.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "placement groups" }
   ],
   "targets": [
    {
     "expr": "sum(ray_placement_groups{SessionName=~\"$SessionName\",}) by (State)",
     "legendFormat": "{{State}}"
    }
   ]
  },
  {
   "title": "Node CPU (hardware utilization)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "ray_node_cpu_utilization{instance=~\"$Instance\",SessionName=~\"$SessionName\",} * ray_node_cpu_count{instance=~\"$Instance\",SessionName=~\"$SessionName\",} / 100",
     "legendFormat": "CPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_node_cpu_count{SessionName=~\"$SessionName\",})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node GPU (hardware utilization)",
   "type": "graph",
   "description": "Node's physical (hardware) GPU usage. The dotted line means the total number of hardware GPUs from the cluster. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "GPUs" }
   ],
   "targets": [
    {
     "expr": "ray_node_gpus_utilization{instance=~\"$Instance\",SessionName=~\"$SessionName\",} / 100",
     "legendFormat": "GPU Usage: {{instance}}, gpu.{{GpuIndex}}, {{GpuDeviceName}}"
    },
    {
     "expr": "sum(ray_node_gpus_available{SessionName=~\"$SessionName\",})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Disk",
   "type": "graph",
   "description": "Node's physical (hardware) disk usage. The dotted line means the total amount of disk space from the cluster.\n\nNOTE: When Ray is deployed within a container, this shows the disk usage from the host machine. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_disk_usage{instance=~\"$Instance\",SessionName=~\"$SessionName\",}",
     "legendFormat": "Disk Used: {{instance}}"
    },
    {
     "expr": "sum(ray_node_disk_free{SessionName=~\"$SessionName\",}) + sum(ray_node_disk_usage{SessionName=~\"$SessionName\",})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Disk IO Speed",
   "type": "graph",
   "description": "Disk IO per node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ray_node_disk_io_write_speed{instance=~\"$Instance\",SessionName=~\"$SessionName\",}",
     "legendFormat": "Write: {{instance}}"
    },
    {
     "expr": "ray_node_disk_io_read_speed{instance=~\"$Instance\",SessionName=~\"$SessionName\",}",
     "legendFormat": "Read: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory (heap + object store)",
   "type": "graph",
   "description": "The physical (hardware) memory usage for each node. The dotted line means the total amount of memory from the cluster. Node memory is a sum of object store memory (shared memory) and heap memory.\n\nNote: If Ray is deployed within a container, the total memory could be lower than the host machine because Ray may reserve some additional memory space outside the container.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_mem_used{instance=~\"$Instance\",SessionName=~\"$SessionName\",}",
     "legendFormat": "Memory Used: {{instance}}"
    },
    {
     "expr": "sum(ray_node_mem_total{SessionName=~\"$SessionName\",})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Out of Memory Failures by Name",
   "type": "graph",
   "description": "The number of tasks and actors killed by the Ray Out of Memory killer due to high memory pressure. Metrics are broken down by IP and the name. https://docs.ray.io/en/master/ray-core/scheduling/ray-oom-prevention.html.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "failures" }
   ],
   "targets": [
    {
     "expr": "ray_memory_manager_worker_eviction_total{instance=~\"$Instance\",SessionName=~\"$SessionName\",}",
     "legendFormat": "OOM Killed: {{Name}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory by Component",
   "type": "graph",
   "description": "The physical (hardware) memory usage across the cluster, broken down by component. This reports the summed RSS-SHM per Ray component, which corresponds to an approximate memory usage per proc. Ray components consist of system components (e.g., raylet, gcs, dashboard, or agent) and the process (that contains method names) names of running tasks/actors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(sum(ray_component_rss_mb{SessionName=~\"$SessionName\",} * 1e6) by (Component)) - (sum(ray_component_mem_shared_bytes{SessionName=~\"$SessionName\",}) by (Component))",
     "legendFormat": "{{Component}}"
    },
    {
     "expr": "sum(ray_node_mem_shared_bytes{SessionName=~\"$SessionName\",})",
     "legendFormat": "shared_memory"
    },
    {
     "expr": "sum(ray_node_mem_total{SessionName=~\"$SessionName\",})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node CPU by Component",
   "type": "graph",
   "description": "The physical (hardware) CPU usage across the cluster, broken down by component. This reports the summed CPU usage per Ray component. Ray components consist of system components (e.g., raylet, gcs, dashboard, or agent) and the process (that contains method names) names of running tasks/actors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_component_cpu_percentage{SessionName=~\"$SessionName\",}) by (Component) / 100",
     "legendFormat": "{{Component}}"
    },
    {
     "expr": "sum(ray_node_cpu_count{SessionName=~\"$SessionName\",})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node GPU Memory (GRAM)",
   "type": "graph",
   "description": "The physical (hardware) GPU memory usage for each node. The dotted line means the total amount of GPU memory from the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_gram_used{instance=~\"$Instance\",SessionName=~\"$SessionName\",} * 1024 * 1024",
     "legendFormat": "Used GRAM: {{instance}}, gpu.{{GpuIndex}}, {{GpuDeviceName}}"
    },
    {
     "expr": "(sum(ray_node_gram_available{SessionName=~\"$SessionName\",}) + sum(ray_node_gram_used{SessionName=~\"$SessionName\",})) * 1024 * 1024",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Network",
   "type": "graph",
   "description": "Network speed per node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ray_node_network_receive_speed{instance=~\"$Instance\",SessionName=~\"$SessionName\",}",
     "legendFormat": "Recv: {{instance}}"
    },
    {
     "expr": "ray_node_network_send_speed{instance=~\"$Instance\",SessionName=~\"$SessionName\",}",
     "legendFormat": "Send: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "graph",
   "description": "A total number of active failed, and pending nodes from the cluster. \n\nACTIVE: A node is alive and available.\n\nFAILED: A node is dead and not available. The node is considered dead when the raylet process on the node is terminated. The node will get into the failed state if it cannot be provided (e.g., there's no available node from the cloud provider) or failed to setup (e.g., setup_commands have errors). \n\nPending: A node is being started by the Ray cluster launcher. The node is unavailable now because it is being provisioned and initialized.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "nodes" }
   ],
   "targets": [
    {
     "expr": "sum(autoscaler_active_nodes{SessionName=~\"$SessionName\",}) by (NodeType)",
     "legendFormat": "Active Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_recently_failed_nodes{SessionName=~\"$SessionName\",}) by (NodeType)",
     "legendFormat": "Failed Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_pending_nodes{SessionName=~\"$SessionName\",}) by (NodeType)",
     "legendFormat": "Pending Nodes: {{NodeType}}"
    }
   ]
  },
  {
   "title": "Cluster Utilization",
   "type": "graph",
   "description": "Aggregated utilization of all physical resources (CPU, GPU, memory, disk, or etc.) across the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "avg(ray_node_cpu_utilization{SessionName=~\"$SessionName\",})",
     "legendFormat": "CPU (physical)"
    },
    {
     "expr": "sum(ray_node_gpus_utilization{SessionName=~\"$SessionName\",}) / on() (sum(autoscaler_cluster_resources{resource='GPU',SessionName=~\"$SessionName\",}) or vector(0))",
     "legendFormat": "GPU (physical)"
    },
    {
     "expr": "sum(ray_node_mem_used{SessionName=~\"$SessionName\",}) / on() (sum(ray_node_mem_total{SessionName=~\"$SessionName\",})) * 100",
     "legendFormat": "Memory (RAM)"
    },
    {
     "expr": "sum(ray_node_gram_used{SessionName=~\"$SessionName\",}) / on() (sum(ray_node_gram_available{SessionName=~\"$SessionName\",}) + sum(ray_node_gram_used{SessionName=~\"$SessionName\",})) * 100",
     "legendFormat": "GRAM"
    },
    {
     "expr": "sum(ray_object_store_memory{SessionName=~\"$SessionName\",}) / on() sum(ray_resources{Name=\"object_store_memory\",SessionName=~\"$SessionName\",}) * 100",
     "legendFormat": "Object Store Memory"
    },
    {
     "expr": "sum(ray_node_disk_usage{SessionName=~\"$SessionName\",}) / on() (sum(ray_node_disk_free{SessionName=~\"$SessionName\",}) + sum(ray_node_disk_usage{SessionName=~\"$SessionName\",})) * 100",
     "legendFormat": "Disk"
    }
   ]
  }
 ]
}
{
 "title": "Serve Deployment Dashboard",
 "tags": [ "rayVersion:2.9.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Application",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{}, application)"
    }
   },
   {
    "name": "Deployment",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{application=~\"$Application\",}, deployment)"
    }
   },
   {
    "name": "Replica",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{application=~\"$Application\",deployment=~\"$Deployment\",}, replica)"
    }
   },
   {
    "name": "Route",
    "query": {
     "query": "label_values(ray_serve_deployment_request_counter{deployment=~\"$Deployment\",}, route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Replicas per deployment",
   "type": "graph",
   "description": "Number of replicas per deployment. Ignores \"Route\" variable.",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_replica_healthy{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "QPS per replica",
   "type": "graph",
   "description": "QPS for each replica.",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_request_counter{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (application, deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Error QPS per replica",
   "type": "graph",
   "description": "Error QPS for each replica.",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_error_counter{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (application, deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "P50 latency per replica",
   "type": "graph",
   "description": "P50 latency per replica.",
   "gridPos": { "x": 0, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P90 latency per replica",
   "type": "graph",
   "description": "P90 latency per replica.",
   "gridPos": { "x": 8, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P99 latency per replica",
   "type": "graph",
   "description": "P99 latency per replica.",
   "gridPos": { "x": 16, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Queue size per deployment",
   "type": "graph",
   "description": "Number of requests queued per deployment. Ignores \"Replica\" and \"Route\" variable.",
   "gridPos": { "x": 0, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_queued_queries{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "Pending requests per replica",
   "type": "graph",
   "description": "Pending requests for each replica.",
   "gridPos": { "x": 8, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_replica_pending_queries{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}) by (application, deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Running requests per replica",
   "type": "graph",
   "description": "Current running requests for each replica.",
   "gridPos": { "x": 16, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_replica_processing_queries{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}) by (application, deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Multiplexed models per replica",
   "type": "graph",
   "description": "The number of multiplexed models for each replica.",
   "gridPos": { "x": 0, "y": 3, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "models" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_num_multiplexed_models{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}) by (application, deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Multiplexed model loads per replica",
   "type": "graph",
   "description": "The number of times of multiplexed models loaded for each replica.",
   "gridPos": { "x": 8, "y": 3, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "times" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_multiplexed_models_load_counter{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}) by (application, deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Multiplexed model unloads per replica",
   "type": "graph",
   "description": "The number of times of multiplexed models unloaded for each replica.",
   "gridPos": { "x": 16, "y": 3, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "times" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_multiplexed_models_unload_counter{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}) by (application, deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "P99 latency of multiplexed model loads per replica",
   "type": "graph",
   "description": "P99 latency of mutliplexed model load per replica.",
   "gridPos": { "x": 0, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_multiplexed_model_load_latency_ms_bucket{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "P99 latency of multiplexed model unloads per replica",
   "type": "graph",
   "description": "P99 latency of mutliplexed model unload per replica.",
   "gridPos": { "x": 8, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_multiplexed_model_unload_latency_ms_bucket{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Multiplexed model ids per replica",
   "type": "graph",
   "description": "The ids of multiplexed models for each replica.",
   "gridPos": { "x": 16, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "model" }
   ],
   "targets": [
    {
     "expr": "ray_serve_registered_multiplexed_model_id{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}",
     "legendFormat": "{{replica}}:{{model_id}}"
    }
   ]
  },
  {
   "title": "Multiplexed model cache hit rate",
   "type": "graph",
   "description": "The cache hit rate of multiplexed models for the deployment.",
   "gridPos": { "x": 0, "y": 5, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(rate(ray_serve_multiplexed_models_load_counter{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m]))/sum(rate(ray_serve_multiplexed_get_model_requests_counter{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])))",
     "legendFormat": "{{replica}}"
    }
   ]
  }
 ]
}
{
 "title": "Serve Dashboard",
 "tags": [ "rayVersion:2.9.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Application",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{}, application)"
    }
   },
   {
    "name": "HTTP_Route",
    "label": "HTTP Route",
    "query": {
     "query": "label_values(ray_serve_num_http_requests{}, route)"
    }
   },
   {
    "name": "gRPC_Method",
    "label": "gRPC Service Method",
    "query": {
     "query": "label_values(ray_serve_num_grpc_requests{}, method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Utilization",
   "type": "graph",
   "description": "Aggregated utilization of all physical resources (CPU, GPU, memory, disk, or etc.) across the cluster. Ignores application variable.",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "avg(ray_node_cpu_utilization{})",
     "legendFormat": "CPU (physical)"
    },
    {
     "expr": "sum(ray_node_gpus_utilization{}) / on() (sum(autoscaler_cluster_resources{resource='GPU',}) or vector(0))",
     "legendFormat": "GPU (physical)"
    },
    {
     "expr": "sum(ray_node_mem_used{}) / on() (sum(ray_node_mem_total{})) * 100",
     "legendFormat": "Memory (RAM)"
    },
    {
     "expr": "sum(ray_node_gram_used{}) / on() (sum(ray_node_gram_available{}) + sum(ray_node_gram_used{})) * 100",
     "legendFormat": "GRAM"
    },
    {
     "expr": "sum(ray_object_store_memory{}) / on() sum(ray_resources{Name=\"object_store_memory\",}) * 100",
     "legendFormat": "Object Store Memory"
    },
    {
     "expr": "sum(ray_node_disk_usage{}) / on() (sum(ray_node_disk_free{}) + sum(ray_node_disk_usage{})) * 100",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "QPS per application",
   "type": "graph",
   "description": "QPS for each selected application.",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_num_http_requests{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",}[5m])) by (application, route)",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "sum(rate(ray_serve_num_grpc_requests{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",}[5m])) by (application, method)",
     "legendFormat": "{{application, method}}"
    }
   ]
  },
  {
   "title": "Error QPS per application",
   "type": "graph",
   "description": "Error QPS for each selected application.",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_num_http_error_requests{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",}[5m])) by (application, route)",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "sum(rate(ray_serve_num_grpc_error_requests{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",}[5m])) by (application, method)",
     "legendFormat": "{{application, method}}"
    }
   ]
  },
  {
   "title": "P50 latency per application",
   "type": "graph",
   "description": "P50 latency for selected applications.",
   "gridPos": { "x": 0, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_http_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",}[5m])) by (application, route, le))",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_grpc_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",}[5m])) by (application, method, le))",
     "legendFormat": "{{application, method}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate({__name__=~ \"ray_serve_(http|grpc)_request_latency_ms_bucket\",application=~\"$Application\",application!~\"\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P90 latency per application",
   "type": "graph",
   "description": "P90 latency for selected applications.",
   "gridPos": { "x": 8, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_http_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",}[5m])) by (application, route, le))",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_grpc_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",}[5m])) by (application, method, le))",
     "legendFormat": "{{application, method}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate({__name__=~ \"ray_serve_(http|grpc)_request_latency_ms_bucket|ray_serve_grpc_request_latency_ms_bucket\",application=~\"$Application\",application!~\"\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P99 latency per application",
   "type": "graph",
   "description": "P99 latency for selected applications.",
   "gridPos": { "x": 16, "y": 1, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_http_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",route=~\"$HTTP_Route\",route!~\"/-/.*\",}[5m])) by (application, route, le))",
     "legendFormat": "{{application, route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_grpc_request_latency_ms_bucket{application=~\"$Application\",application!~\"\",method=~\"$gRPC_Method\",}[5m])) by (application, method, le))",
     "legendFormat": "{{application, method}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate({__name__=~ \"ray_serve_(http|grpc)_request_latency_ms_bucket|ray_serve_grpc_request_latency_ms_bucket\",application=~\"$Application\",application!~\"\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Replicas per deployment",
   "type": "graph",
   "description": "Number of replicas per deployment. Ignores \"Application\" variable.",
   "gridPos": { "x": 0, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_replica_healthy{}) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "QPS per deployment",
   "type": "graph",
   "description": "QPS for each deployment.",
   "gridPos": { "x": 8, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_request_counter{application=~\"$Application\",application!~\"\",}[5m])) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "Error QPS per deployment",
   "type": "graph",
   "description": "Error QPS for each deplyoment.",
   "gridPos": { "x": 16, "y": 2, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "qps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_error_counter{application=~\"$Application\",application!~\"\",}[5m])) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "P50 latency per deployment",
   "type": "graph",
   "description": "P50 latency per deployment.",
   "gridPos": { "x": 0, "y": 3, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",}[5m])) by (application, deployment, le))",
     "legendFormat": "{{application, deployment}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P90 latency per deployment",
   "type": "graph",
   "description": "P90 latency per deployment.",
   "gridPos": { "x": 8, "y": 3, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",}[5m])) by (application, deployment, le))",
     "legendFormat": "{{application, deployment}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P99 latency per deployment",
   "type": "graph",
   "description": "P99 latency per deployment.",
   "gridPos": { "x": 16, "y": 3, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",}[5m])) by (application, deployment, le))",
     "legendFormat": "{{application, deployment}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{application=~\"$Application\",application!~\"\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Queue size per deployment",
   "type": "graph",
   "description": "Number of requests queued per deployment. Ignores \"Application\" variable.",
   "gridPos": { "x": 0, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_queued_queries{}) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "graph",
   "description": "Number of nodes in this cluster. Ignores \"Application\" variable.",
   "gridPos": { "x": 8, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "nodes" }
   ],
   "targets": [
    {
     "expr": "sum(autoscaler_active_nodes{}) by (NodeType)",
     "legendFormat": "Active Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_recently_failed_nodes{}) by (NodeType)",
     "legendFormat": "Failed Nodes: {{NodeType}}"
    },
    {
     "expr": "sum(autoscaler_pending_nodes{}) by (NodeType)",
     "legendFormat": "Pending Nodes: {{NodeType}}"
    }
   ]
  },
  {
   "title": "Node network",
   "type": "graph",
   "description": "Network speed per node. Ignores \"Application\" variable.",
   "gridPos": { "x": 16, "y": 4, "w": 8, "h": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(ray_node_network_receive_speed{}) by (instance)",
     "legendFormat": "Recv: {{instance}}"
    },
    {
     "expr": "sum(ray_node_network_send_speed{}) by (instance)",
     "legendFormat": "Send: {{instance}}"
    }
   ]
  }
 ]
}