---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: first-node-placement
  namespace: kgateway-system
spec:
  kube:
    podTemplate:
      nodeSelector:
        cluster-bloom/first-node: "true"