{{- if and .Values.externalSecrets.enabled .Values.cnpg.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.postgresql.userSecretName }}-credentials
  namespace: keycloak
spec:
  data:
    - remoteRef:
        key: keycloak-cnpg-user-username
        property: value
      secretKey: username
    - remoteRef:
        key: keycloak-cnpg-user-password
        property: value
      secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    creationPolicy: Owner
    name: {{ .Values.postgresql.userSecretName }}
{{- end }}
