---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-cnpg-superuser-credentials
  namespace: keycloak
spec:
  data:
    - remoteRef:
        key: keycloak-cnpg-superuser-username
      secretKey: username
    - remoteRef:
        key: keycloak-cnpg-superuser-password
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: airm-secret-store
  target:
    creationPolicy: Owner
    name: keycloak-cnpg-superuser
