---
apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ .Release.Name }}-secret-generator'
  namespace: '{{ .Release.Namespace }}'
spec:
  template:
    spec:
      serviceAccountName: '{{ .Release.Name }}-secret-generator-sa'
      containers:
      - name: secret-generator
        image: {{ .Values.secretGenerator.image }}
        command: ["/bin/bash"]
        args: ["/scripts/generate-secrets.sh"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: '{{ .Release.Name }}-secret-generator-script'
          defaultMode: 0755
      restartPolicy: OnFailure
  backoffLimit: 3
