apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodeexporter-chrony-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: chrony-exporter
spec:
  selector:
    matchLabels:
      app: chrony-exporter
  template:
    metadata:
      labels:
        app: chrony-exporter
    spec:
      containers:
        - name: chrony-exporter
          image: quay.io/superq/chrony-exporter:v0.12.1
          args:
            - "--chrony.address=unix:///run/chrony/chronyd.sock"
            - "--collector.chmod-socket"
            - "--collector.sources"
            - "--collector.tracking"
            - "--log.level=info"
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 9123
              name: metrics
              protocol: TCP
          volumeMounts:
            - mountPath: /run/chrony/
              name: chronyd-socket
          resources:
            limits:
{{- if .Values.nodeExporter.chrony.resources.limits.cpu }}
              cpu: {{ .Values.nodeExporter.chrony.resources.limits.cpu | quote }}
{{- end }}
              memory: {{ .Values.nodeExporter.chrony.resources.limits.memory }}
            requests:
              cpu: {{ .Values.nodeExporter.chrony.resources.requests.cpu | quote }}
              memory: {{ .Values.nodeExporter.chrony.resources.requests.memory }}
      volumes:
        - name: chronyd-socket
          hostPath:
            path: /run/chrony/
            type: Directory
