# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: aim.eai.amd.com/v1alpha1
kind: AIMClusterModelSource
metadata:
  name: amd-aim-release-0.10.0
spec:
  filters:
  - image: amdenterpriseai/aim-coherelabs-command-a-reasoning-08-2025:0.10.0
  - image: amdenterpriseai/aim-deepseek-ai-deepseek-r1-0528:0.10.0
  - image: amdenterpriseai/aim-deepseek-ai-deepseek-r1:0.10.0
  - image: amdenterpriseai/aim-deepseek-ai-deepseek-v3-1-terminus:0.10.0
  - image: amdenterpriseai/aim-deepseek-ai-deepseek-v3-1:0.10.0
  - image: amdenterpriseai/aim-meta-llama-llama-3-1-405b-instruct:0.10.0
  - image: amdenterpriseai/aim-meta-llama-llama-3-1-8b-instruct:0.10.0
  - image: amdenterpriseai/aim-meta-llama-llama-3-2-1b-instruct:0.10.0
  - image: amdenterpriseai/aim-meta-llama-llama-3-2-3b-instruct:0.10.0
  - image: amdenterpriseai/aim-meta-llama-llama-3-3-70b-instruct:0.10.0
  - image: amdenterpriseai/aim-mistralai-ministral-3-14b-instruct-2512:0.10.0
  - image: amdenterpriseai/aim-mistralai-mistral-large-3-675b-instruct-2512:0.10.0
  - image: amdenterpriseai/aim-mistralai-mistral-small-3-2-24b-instruct-2506:0.10.0
  - image: amdenterpriseai/aim-mistralai-mixtral-8x22b-instruct-v0-1:0.10.0
  - image: amdenterpriseai/aim-mistralai-mixtral-8x7b-instruct-v0-1:0.10.0
  - image: amdenterpriseai/aim-openai-gpt-oss-120b:0.10.0
  - image: amdenterpriseai/aim-openai-gpt-oss-20b:0.10.0
  - image: amdenterpriseai/aim-qwen-qwen3-235b-a22b:0.10.0
  - image: amdenterpriseai/aim-qwen-qwen3-32b:0.10.0
  maxModels: 100
  registry: docker.io
  syncInterval: 1h
