# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModelSource
metadata:
  name: amd-aim-release-0.9.0
spec:
  filters:
    - image: amdenterpriseai/aim-base:0.9
    - image: amdenterpriseai/aim-coherelabs-command-a-reasoning-08-2025:0.9.0
    - image: amdenterpriseai/aim-openai-gpt-oss-20b:0.9.0
    - image: amdenterpriseai/aim-openai-gpt-oss-120b:0.9.0
    - image: amdenterpriseai/aim-qwen-qwen3-235b-a22b:0.9.0
  maxModels: 100
  registry: docker.io
  syncInterval: 1h
