{
 "title": "ArgoCD dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "k8s_cluster_name", "label": "k8s_cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(argocd_app_info,namespace)"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(argocd_app_info,project)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Argocd_cluster_info",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argocd_cluster_info{k8s_cluster_name=~\"$k8s_cluster_name\"}\n",
     "legendFormat": "{{k8s_cluster_name}},  k8s_version:{{k8s_version}}"
    }
   ]
  },
  {
   "title": "Number of Argocd apps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(k8s_cluster_name) (argocd_app_info{k8s_cluster_name=\"$k8s_cluster_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(health_status) (argocd_app_info{k8s_cluster_name=~\"$k8s_cluster_name\"})\n\n"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(sync_status) (argocd_app_info{k8s_cluster_name=~\"$k8s_cluster_name\"})\n"
    }
   ]
  },
  {
   "title": "Applications_out_of_sync",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "argocd_app_info{k8s_cluster_name=~\"$k8s_cluster_name\", sync_status=\"OutOfSync\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applications_not_healthy",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "argocd_app_info{k8s_cluster_name=~\"$k8s_cluster_name\", health_status!~\"Healthy\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}