apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-devuser-secret
  namespace: cf-gitea
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  refreshInterval: 5m
  target:
    name: gitea-devuser-secret
  data:
    - remoteRef:
        key: gitea-devuser-secret
        property: value
      secretKey: GITEA_DEVUSER_SECRET
