# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

---
apiVersion: v2
name: aiwb-external-secrets
description: ExternalSecret resources for AIWB application secrets

type: application

version: 0.1.1

appVersion: "0.1.1"
