apiVersion: v2
name: seaweedfs
description: Optional S3 object storage, a Seaweed cluster and a bucket
type: application
version: 0.1.0
dependencies:
  - name: seaweedfs-config
    version: 0.1.0
    repository: file://../../../sources/seaweedfs-config
