{{- with .Values.seaweed }}
apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed
  namespace: seaweedfs-instance
spec:
  image: chrislusf/seaweedfs:latest
  volumeServerDiskCount: 1
  hostSuffix: plat-dev-1.silogen.ai
  master:
    replicas: {{ .master.replicas }}
    volumeSizeLimitMB: 1024
  volume:
    replicas: {{ .volume.replicas }}
    storageClassName: {{ .storageClassName }}
    requests:
      storage: {{ .volume.requests.storage }}
    # Topology configuration for rack/datacenter-aware placement
    rack: "rack1"
    dataCenter: "dc1"
  filer:
    replicas: {{ .filer.replicas }}
    volumes:
      - name: s3-metadata
        persistentVolumeClaim:
          claimName: pvc-seaweed-s3-metadata
    volumeMounts:
      - mountPath: /data/
        name: s3-metadata
    s3:
      enabled: true
      configSecret:
        name: seaweedfs-s3-config
        key: s3.json
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"
{{- end}}