{{- with .Values.bucket }}
apiVersion: seaweed.seaweedfs.com/v1
kind: Bucket
metadata:
  name: {{ .name }}
  namespace: seaweedfs-instance
spec:
  clusterRef:
    name: seaweed
    namespace: seaweedfs-instance
  reclaimPolicy: Retain
  versioning: Off
  adoptExisting: true
  objectLock: false
{{- end }}
