apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    creationPolicy: Owner
    name: grafana-admin-credentials
  data:
    - secretKey: username
      remoteRef:
        key: grafana-admin-user
        property: value
    - secretKey: password
      remoteRef:
        key: grafana-admin-password
        property: value
