# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

airm:
  # Shared configuration between agent and webhook
  image:
    repository: ghcr.io/silogen/core/airm-agent
    tag: 1.0.2
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  agent:
    servicePort: 8000
    rabbitmq:
      host: "airm-infra-rabbitmq-rabbitmq.airm.svc.cluster.local"
      port: 5672
      userSecretName: "airm-rabbitmq-common-vhost-user"
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
  webhook:
    servicePort: 9443
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
  utilities:
    netcat:
      image:
        repository: busybox
        tag: 1.37.0
        pullPolicy: IfNotPresent
    curl:
      image:
        repository: curlimages/curl
        tag: 8.16.0
        pullPolicy: IfNotPresent
  additionalClusterRoles:
    platformAdmin: []
    projectMember: []
