apiVersion: v2
name: amd-gpu-operator-config
description: The DeviceConfig object that turns the AMD GPU operator on for a node
type: application
version: 0.1.0
dependencies:
  - name: amd-gpu-operator-config
    version: 0.1.0
    repository: file://../../../sources/amd-gpu-operator-config/v1.4.1
