---
apiVersion: v1
kind: Service
metadata:
  name: gw-ext-adapter
  namespace: demo #testing-gw-ext-adapter
spec:
  selector:
    app: gw-ext-adapter
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-ext-adapter
  namespace: demo #testing-gw-ext-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gw-ext-adapter
  template:
    metadata:
      labels:
        app: gw-ext-adapter
    spec:
      containers:
      - name: grpc-authz-adapter
        image: ttl.sh/grpc-authz-adapter-v0.0.3:24h # TODO: Compile and put new image here
        imagePullPolicy: IfNotPresent
        env:
        - name: KEYCLOAK_SERVER_URL
          value: "https://kc.app-dev.silogen.ai"
        - name: KEYCLOAK_REALM
          value: "airm"
        - name: KEYCLOAK_CLIENT_ID
          value: "354a0fa1-35ac-4a6d-9c4d-d661129c2cd0"
        - name: LISTEN_ADDR
          value: ":50051"
        - name: WORKLOAD_URL
          value: "workloads.app-dev.silogen.ai"
        ports:
        - containerPort: 50051

---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: gw-ext-adapter-extension
  namespace: demo
spec:
  type: ExtAuth
  extAuth:
    grpcService:
      backendRef:
        name: gw-ext-adapter
        port: 50051
        namespace: demo #testing-gw-ext-adapter

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-demo-to-gw-ext-adapter
  namespace: demo
spec:
  from:
  - group: gateway.kgateway.dev
    kind: GatewayExtension
    namespace: demo
  - group: gateway.kgateway.dev
    kind: TrafficPolicy
    namespace: demo
  to:
  - group: ""   # core API group
    kind: Service
    name: gw-ext-adapter

---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: policy-test-auth
  namespace: demo
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: <PUT-A-VALID-HTTP-ROUTE-HERE>
  extAuth:
    extensionRef: 
      name: gw-ext-adapter-extension
