apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-readonly
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - secretstores
  - clustersecretstores
  - externalsecrets
  - clusterexternalsecrets
  verbs:
  - get
  - list
  - watch
