apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: clusterforge-password-generator
spec:
  kind: Password
  generator:
    passwordSpec:
      allowRepeat: true
      digits: 5
      length: 24
      noUpper: false
      symbolCharacters: _/
      symbols: 5
